[package]
name = "chessrl"
version = "0.0.1"
authors = ["frgmt0 <jason.awz2005@icloud.com>"]
description = "A chess engine/game written in Rust"
license = "MIT"
edition = "2021"

[dependencies]
crossterm = "0.25"
colored = "2.0"
rand = "0.8.5"
ratatui = "0.29.0"
